/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportLostRouteImport } from './routes/report-lost'
import { Route as ReportFoundRouteImport } from './routes/report-found'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LostPetsRouteImport } from './routes/lost-pets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HappyTailsRouteImport } from './routes/happy-tails'
import { Route as FoundPetsRouteImport } from './routes/found-pets'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'

const ReportLostRoute = ReportLostRouteImport.update({
  id: '/report-lost',
  path: '/report-lost',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFoundRoute = ReportFoundRouteImport.update({
  id: '/report-found',
  path: '/report-found',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LostPetsRoute = LostPetsRouteImport.update({
  id: '/lost-pets',
  path: '/lost-pets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HappyTailsRoute = HappyTailsRouteImport.update({
  id: '/happy-tails',
  path: '/happy-tails',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundPetsRoute = FoundPetsRouteImport.update({
  id: '/found-pets',
  path: '/found-pets',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/found-pets': typeof FoundPetsRoute
  '/happy-tails': typeof HappyTailsRoute
  '/login': typeof LoginRoute
  '/lost-pets': typeof LostPetsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/found-pets': typeof FoundPetsRoute
  '/happy-tails': typeof HappyTailsRoute
  '/login': typeof LoginRoute
  '/lost-pets': typeof LostPetsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/found-pets': typeof FoundPetsRoute
  '/happy-tails': typeof HappyTailsRoute
  '/login': typeof LoginRoute
  '/lost-pets': typeof LostPetsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/found-pets'
    | '/happy-tails'
    | '/login'
    | '/lost-pets'
    | '/profile'
    | '/register'
    | '/report-found'
    | '/report-lost'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/found-pets'
    | '/happy-tails'
    | '/login'
    | '/lost-pets'
    | '/profile'
    | '/register'
    | '/report-found'
    | '/report-lost'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/found-pets'
    | '/happy-tails'
    | '/login'
    | '/lost-pets'
    | '/profile'
    | '/register'
    | '/report-found'
    | '/report-lost'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  FoundPetsRoute: typeof FoundPetsRoute
  HappyTailsRoute: typeof HappyTailsRoute
  LoginRoute: typeof LoginRoute
  LostPetsRoute: typeof LostPetsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportFoundRoute: typeof ReportFoundRoute
  ReportLostRoute: typeof ReportLostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report-lost': {
      id: '/report-lost'
      path: '/report-lost'
      fullPath: '/report-lost'
      preLoaderRoute: typeof ReportLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-found': {
      id: '/report-found'
      path: '/report-found'
      fullPath: '/report-found'
      preLoaderRoute: typeof ReportFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-pets': {
      id: '/lost-pets'
      path: '/lost-pets'
      fullPath: '/lost-pets'
      preLoaderRoute: typeof LostPetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/happy-tails': {
      id: '/happy-tails'
      path: '/happy-tails'
      fullPath: '/happy-tails'
      preLoaderRoute: typeof HappyTailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found-pets': {
      id: '/found-pets'
      path: '/found-pets'
      fullPath: '/found-pets'
      preLoaderRoute: typeof FoundPetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  FoundPetsRoute: FoundPetsRoute,
  HappyTailsRoute: HappyTailsRoute,
  LoginRoute: LoginRoute,
  LostPetsRoute: LostPetsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportFoundRoute: ReportFoundRoute,
  ReportLostRoute: ReportLostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
